name: Run Flow
description: 'Execute a named Cumulus flow'
inputs:
  org-name:
    description: 'Name of the scratch org or persistent org config to use'
    required: true
  flow-name:
    description: 'Name of the Cumulus flow to execute'
    required: true
  delete-scratch-org:
    description: 'Specify whether to delete the Scratch org'
    required: false
    default: true
runs:
    using: "composite"
    steps:
      - name: Add IP range to System Admin Profile
        if: ${{ (inputs.delete-scratch-org == 'false' }}
        run: |
          mkdir -p profiles
          cat <<EOF > profiles/Admin.profile-meta.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <Profile xmlns="http://soap.sforce.com/2006/04/metadata">
              <loginIpRanges>
                  <description>Allow All</description>
                  <endAddress>255.255.255.255</endAddress>
                  <startAddress>0.0.0.0</startAddress>
              </loginIpRanges>
          </Profile>
          EOF
          cci task run deploy --path profiles/ --org ${{ inputs.org-name }}
        shell: bash
      - name: Run Flow
        run: |
          if [ "${{ inputs.delete-scratch-org }}" = "true" ]; then
            cci flow run ${{ inputs.flow-name }} --org ${{ inputs.org-name }} | tee cumulusci-flow.log
          else
            cci org info '${{ inputs.org-name }}'
            cci flow run spin_up_test --org ${{ inputs.org-name }} | tee cumulusci-flow.log
          fi
        shell: bash
